name: Terraform infra plan

on:
  push
env:
  BUCKET_NAME : "clearslide-dev-video"
  AWS_REGION : "us-west-2"

permissions:
  id-token: write
  contents: read
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::707613674397:role/GitHubRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          touch action.txt
          aws s3 cp action.txt s3://${{ env.BUCKET_NAME }}/
