name: Terraform infra plan

on:
  pull_request:
    paths:
      - 'terraform/aws/us-east-1/**/*.tf*'


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_PACKER_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_PACKER_AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix: { regions: [ "us-east-1", "us-west-2" ], envs: ["production", "staging"] }
    defaults:
      run:
        working-directory: terraform/aws/${{ matrix.regions }}/${{ matrix.envs }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: hashicorp/setup-terraform@v1
      - run: pwd
#      - run: terraform plan
#        id: plan
#      - uses: theappnest/create-artifact-action@5ce25c02358af7c7f81fb297bd2b5b621434dc77
#        with:
#          name: terraform-plan
#          path: ${{ matrix.module }}
#          content: ${{ steps.plan.outputs.stdout }}
#  comment:
#    runs-on: ubuntu-latest
#    needs: terraform
#    steps:
#      - uses: theappnest/terraform-plan-comment-action@3fbaf59b753c1688dfe549be4a14fddb7a497a69
#        with:
#          name: terraform-plan
