name: Terraform infra plan

on:
  pull_request:
    paths:
      - 'terraform/aws/us-east-1/production/*.tf*'


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_PACKER_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_PACKER_AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix: { regions: [ "us-east-1" ], envs: ["production"] }
    defaults:
      run:
        working-directory: terraform/aws/${{ matrix.regions }}/${{ matrix.envs }}
    steps:
      - name: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: setup tf
        uses: hashicorp/setup-terraform@97360ea1641076c763cc0b38c4e673ffc686b42c
      - name: init
        run: terraform init
      - name: plan
        run: terraform plan -out workspace.plan
        id: plan
      - name: comment
        uses: robburger/terraform-pr-commenter@v1
        with:
          commenter_type: plan
          commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
#      - uses: theappnest/create-artifact-action@5ce25c02358af7c7f81fb297bd2b5b621434dc77
#        with:
#          name: terraform-plan
#          path: ${{ matrix.module }}
#          content: ${{ steps.plan.outputs.stdout }}
#  comment:
#    runs-on: ubuntu-latest
#    needs: terraform
#    steps:
#      - uses: theappnest/terraform-plan-comment-action@3fbaf59b753c1688dfe549be4a14fddb7a497a69
#        with:
#          name: terraform-plan
