name: Terraform infra plan

on:
  pull_request:
    paths:
      - 'terraform/aws/us-east-1/production/*.tf*'
env:
  AWS_REGION : "us-east-1"

permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix: { regions: [ "us-east-1" ], envs: ["production"] }
    defaults:
      run:
        working-directory: terraform/aws/${{ matrix.regions }}/${{ matrix.envs }}
    steps:
      - name: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::707613674397:role/GitHubRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: setup tf
        uses: hashicorp/setup-terraform@97360ea1641076c763cc0b38c4e673ffc686b42c
      - name: init
        run: terraform init
      - name: plan
        run: terraform plan -out workspace.plan
        id: plan
      - name: comment
        uses: theappnest/terraform-plan-comment-action@3fbaf59b753c1688dfe549be4a14fddb7a497a69
        with:
          plan: ${{ steps.plan.outputs.stdout }}
